spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    schemas: ${SPRING_FLYWAY_SCHEMAS}
    clean-disabled: ${FLYWAY_CLEAN_DISABLED}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: always

server:
  port: ${SERVER_PORT}


jwt:
  access: ${JWT_ACCESS}
  refresh: ${JWT_REFRESH}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

actuator:
  key: ${ACTUATOR_KEY}